### ISSUE TITLE
"Cannot import" error in ComfyUI log

### ISSUE THREAD

**Issue by fafayqa** [rubi-du/ComfyUI-Flux-Inpainting#2]
I am using latest ComfyUI Portable v0.3.9.10 (https://github.com/comfyanonymous/ComfyUI/releases) .

[2024-12-22 20:06:26.289] Cannot import Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
[2024-12-22 20:06:26.301] ### Loading: ComfyUI-Impact-Pack (V8.1.5)
[2024-12-22 20:06:26.311] Traceback (most recent call last):
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 50, in <module>
    import impact.impact_server  # to load server api
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 12, in <module>
    import impact.core as core
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 7, in <module>
    from segment_anything import SamPredictor
ModuleNotFoundError: No module named 'segment_anything'

**Comment by rubi-du** [comment]
Maybe it's caused by the low version of your local huggingface'hub package. You can upgrade this package and try it out

**Comment by fafayqa** [comment]
> You can upgrade this package and try it out

And how to do that, please?

Oh, I checked and i do have the latest version:

Name: huggingface-hub
Version: 0.27.0

**Comment by rubi-du** [comment]
@fafayqa Can you provide transformer and diffusers versions， I saw that the hugginface hub removed the cached_download function after version 0.26.0，I think you can fix it in the following three ways

1. Upgrade transformers and diffusers packages to adapt to the latest version of hugginface_hub
2. Reduce the version of the hugginface hub package to below 0.26.0
3. The best way is to manually download the model to the specified directory, which can avoid downloading at runtime
